Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,29 +11,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Kodu al
-      - name: Checkout Code
-        uses: actions/checkout@v4
-
-      # FortiClient VPN bağlantısı
-      - name: Forticlient VPN
-        uses: horellana/openconnect@v1.0.1
-        with:
-          VPN_USER: ${{ secrets.VPN_USER }}
-          VPN_PWD: ${{ secrets.VPN_PWD }}
-          VPN_HOST: ${{ secrets.VPN_HOST }}
-          VPN_PORT: 19443
-          VPN_SERVER_CERT: ${{ secrets.VPN_SERVER_CERT }}      
-
-      # VPN bağlantısını doğrula
-      - name: Test VPN Connection
-        run: ifconfig
-
-      # SSH bağlantısını test et
-      - name: Test SSH Connection
+      - name: Install FortiClient
         run: |
-          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PROD_SSH_PORT }} ${{ secrets.PROD_SSH_USERNAME }}@${{ secrets.PROD_SSH_HOST }} echo "SSH connection successful"
+          wget https://links.fortinet.com/forticlient/debian/vpnagent-linux.deb
+          sudo apt-get update
+          sudo apt-get install -y ./vpnagent-linux.deb
 
+      - name: Connect to FortiClient VPN
+        run: |
+          echo "Starting FortiClient VPN..."
+          fortivpn --server ${{ secrets.VPN_HOST }} \
+                   --vpnuser ${{ secrets.VPN_USER }} \
+                   --password ${{ secrets.VPN_PWD }} \
+                   || echo "VPN connection failed." && exit 1      
+    
       # VPN bağlantısından sonra SSH ile komut çalıştırma
       - name: Execute remote SSH commands
         uses: appleboy/ssh-action@master
